# fly.toml app configuration file generated for pajrate-bot on 2026-07-31T01:49:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pajrate-bot'
primary_region = 'ams'

[build]

[env]
  DATA_DIR = '/data'
  PORT = '8080'

[[mounts]]
  source = 'pajrate_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
